apiVersion: clickhousedbops.crossplane.io/v1alpha1
kind: Database
metadata:
  annotations:
    meta.upbound.io/example-id: clickhousedbops/v1alpha1/database
  labels:
    testing.upbound.io/example-name: logs
  name: logs
spec:
  forProvider:
    clusterName: cluster
    name: logs
