apiVersion: clickhousedbops.crossplane.io/v1alpha1
kind: SettingProfileAssociation
metadata:
  annotations:
    meta.upbound.io/example-id: clickhousedbops/v1alpha1/settingprofileassociation
  labels:
    testing.upbound.io/example-name: roleassociation
  name: roleassociation
spec:
  forProvider:
    roleIdSelector:
      matchLabels:
        testing.upbound.io/example-name: role1
    settingsProfileIdSelector:
      matchLabels:
        testing.upbound.io/example-name: profile1
