// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type GrantRoleInitParameters struct {

	// (Boolean) If true, the grantee will be able to grant role_name to other users or roles.
	// If true, the grantee will be able to grant `role_name` to other `users` or `roles`.
	AdminOption *bool `json:"adminOption,omitempty" tf:"admin_option,omitempty"`

	// (String) Name of the cluster to create the resource into. If omitted, resource will be created on the replica hit by the query.
	// This field must be left null when using a ClickHouse Cloud cluster.
	// When using a self hosted ClickHouse instance, this field should only be set when there is more than one replica and you are not using 'replicated' storage for user_directory.
	// Name of the cluster to create the resource into. If omitted, resource will be created on the replica hit by the query.
	// This field must be left null when using a ClickHouse Cloud cluster.
	// When using a self hosted ClickHouse instance, this field should only be set when there is more than one replica and you are not using 'replicated' storage for user_directory.
	ClusterName *string `json:"clusterName,omitempty" tf:"cluster_name,omitempty"`

	// (String) Name of the role to grant role_name to.
	// Name of the `role` to grant `role_name` to.
	GranteeRoleName *string `json:"granteeRoleName,omitempty" tf:"grantee_role_name,omitempty"`

	// (String) Name of the user to grant role_name to.
	// Name of the `user` to grant `role_name` to.
	GranteeUserName *string `json:"granteeUserName,omitempty" tf:"grantee_user_name,omitempty"`

	// (String) Name of the role to be granted
	// Name of the role to be granted
	RoleName *string `json:"roleName,omitempty" tf:"role_name,omitempty"`
}

type GrantRoleObservation struct {

	// (Boolean) If true, the grantee will be able to grant role_name to other users or roles.
	// If true, the grantee will be able to grant `role_name` to other `users` or `roles`.
	AdminOption *bool `json:"adminOption,omitempty" tf:"admin_option,omitempty"`

	// (String) Name of the cluster to create the resource into. If omitted, resource will be created on the replica hit by the query.
	// This field must be left null when using a ClickHouse Cloud cluster.
	// When using a self hosted ClickHouse instance, this field should only be set when there is more than one replica and you are not using 'replicated' storage for user_directory.
	// Name of the cluster to create the resource into. If omitted, resource will be created on the replica hit by the query.
	// This field must be left null when using a ClickHouse Cloud cluster.
	// When using a self hosted ClickHouse instance, this field should only be set when there is more than one replica and you are not using 'replicated' storage for user_directory.
	ClusterName *string `json:"clusterName,omitempty" tf:"cluster_name,omitempty"`

	// (String) Name of the role to grant role_name to.
	// Name of the `role` to grant `role_name` to.
	GranteeRoleName *string `json:"granteeRoleName,omitempty" tf:"grantee_role_name,omitempty"`

	// (String) Name of the user to grant role_name to.
	// Name of the `user` to grant `role_name` to.
	GranteeUserName *string `json:"granteeUserName,omitempty" tf:"grantee_user_name,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Name of the role to be granted
	// Name of the role to be granted
	RoleName *string `json:"roleName,omitempty" tf:"role_name,omitempty"`
}

type GrantRoleParameters struct {

	// (Boolean) If true, the grantee will be able to grant role_name to other users or roles.
	// If true, the grantee will be able to grant `role_name` to other `users` or `roles`.
	// +kubebuilder:validation:Optional
	AdminOption *bool `json:"adminOption,omitempty" tf:"admin_option,omitempty"`

	// (String) Name of the cluster to create the resource into. If omitted, resource will be created on the replica hit by the query.
	// This field must be left null when using a ClickHouse Cloud cluster.
	// When using a self hosted ClickHouse instance, this field should only be set when there is more than one replica and you are not using 'replicated' storage for user_directory.
	// Name of the cluster to create the resource into. If omitted, resource will be created on the replica hit by the query.
	// This field must be left null when using a ClickHouse Cloud cluster.
	// When using a self hosted ClickHouse instance, this field should only be set when there is more than one replica and you are not using 'replicated' storage for user_directory.
	// +kubebuilder:validation:Optional
	ClusterName *string `json:"clusterName,omitempty" tf:"cluster_name,omitempty"`

	// (String) Name of the role to grant role_name to.
	// Name of the `role` to grant `role_name` to.
	// +kubebuilder:validation:Optional
	GranteeRoleName *string `json:"granteeRoleName,omitempty" tf:"grantee_role_name,omitempty"`

	// (String) Name of the user to grant role_name to.
	// Name of the `user` to grant `role_name` to.
	// +kubebuilder:validation:Optional
	GranteeUserName *string `json:"granteeUserName,omitempty" tf:"grantee_user_name,omitempty"`

	// (String) Name of the role to be granted
	// Name of the role to be granted
	// +kubebuilder:validation:Optional
	RoleName *string `json:"roleName,omitempty" tf:"role_name,omitempty"`
}

// GrantRoleSpec defines the desired state of GrantRole
type GrantRoleSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            GrantRoleParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider GrantRoleInitParameters `json:"initProvider,omitempty"`
}

// GrantRoleStatus defines the observed state of GrantRole.
type GrantRoleStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        GrantRoleObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// GrantRole is the Schema for the GrantRoles API. You can use the clickhousedbops_grant_role resource to grant a clickhousedbops_role to either a clickhousedbops_user or to another clickhousedbops_role. Known limitations: It's not possible to grant the same clickhousedbops_role to both a clickhousedbops_user and a clickhousedbops_role using a single clickhousedbops_grant_role stanza. You can do that using two different stanzas, one with grantee_user_name and the other with grantee_role_name fields set.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,clickhousedbops}
type GrantRole struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.roleName) || (has(self.initProvider) && has(self.initProvider.roleName))",message="spec.forProvider.roleName is a required parameter"
	Spec   GrantRoleSpec   `json:"spec"`
	Status GrantRoleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// GrantRoleList contains a list of GrantRoles
type GrantRoleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []GrantRole `json:"items"`
}

// Repository type metadata.
var (
	GrantRole_Kind             = "GrantRole"
	GrantRole_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: GrantRole_Kind}.String()
	GrantRole_KindAPIVersion   = GrantRole_Kind + "." + CRDGroupVersion.String()
	GrantRole_GroupVersionKind = CRDGroupVersion.WithKind(GrantRole_Kind)
)

func init() {
	SchemeBuilder.Register(&GrantRole{}, &GrantRoleList{})
}
