// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *Database) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *GrantPrivilege) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *GrantRole) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Role) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Setting) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *SettingProfile) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *SettingProfileAssociation) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *User) Hub() {}
