// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type GrantPrivilegeInitParameters struct {

	// scoped privileges, or a source name (e.g. S3) for source READ/WRITE grants. Supports a trailing * prefix pattern.
	// The object the privilege applies to: a user/role name for USER_NAME/DEFINER-scoped privileges, or a source name (e.g. `S3`) for source READ/WRITE grants. Supports a trailing `*` prefix pattern.
	AccessObject *string `json:"accessObject,omitempty" tf:"access_object,omitempty"`

	// (String) Name of the cluster to create the resource into. If omitted, resource will be created on the replica hit by the query.
	// This field must be left null when using a ClickHouse Cloud cluster.
	// When using a self hosted ClickHouse instance, this field should only be set when there is more than one replica and you are not using 'replicated' storage for user_directory.
	// Name of the cluster to create the resource into. If omitted, resource will be created on the replica hit by the query.
	// This field must be left null when using a ClickHouse Cloud cluster.
	// When using a self hosted ClickHouse instance, this field should only be set when there is more than one replica and you are not using 'replicated' storage for user_directory.
	ClusterName *string `json:"clusterName,omitempty" tf:"cluster_name,omitempty"`

	// (String) The name of the column in table_name to grant privilege on.
	// The name of the column in `table_name` to grant privilege on.
	ColumnName *string `json:"columnName,omitempty" tf:"column_name,omitempty"`

	// (Boolean) If true, emit GRANT CURRENT GRANTS(...) so the privilege is copied from the grantor's own grants instead of granted directly. Required on ClickHouse Cloud for broad privileges (e.g. ALL, or SELECT on *.*) that the admin user holds but cannot transfer directly. Note: the effective grants depend on what the grantor holds at apply time, so drift on a current_grants grant is not reconciled. On destroy the privilege is revoked in full from the grantee on the target.
	// If true, emit `GRANT CURRENT GRANTS(...)` so the privilege is copied from the grantor's own grants instead of granted directly. Required on ClickHouse Cloud for broad privileges (e.g. `ALL`, or `SELECT` on `*.*`) that the admin user holds but cannot transfer directly. Note: the effective grants depend on what the grantor holds at apply time, so drift on a `current_grants` grant is not reconciled. On destroy the privilege is revoked in full from the grantee on the target.
	CurrentGrants *bool `json:"currentGrants,omitempty" tf:"current_grants,omitempty"`

	// (String) The name of the database to grant privilege on. Defaults to all databases if left null
	// The name of the database to grant privilege on. Defaults to all databases if left null
	DatabaseName *string `json:"databaseName,omitempty" tf:"database_name,omitempty"`

	// (Boolean) If true, the grantee will be able to grant the same privileges to others.
	// If true, the grantee will be able to grant the same privileges to others.
	GrantOption *bool `json:"grantOption,omitempty" tf:"grant_option,omitempty"`

	// (String) Name of the role to grant privileges to.
	// Name of the `role` to grant privileges to.
	GranteeRoleName *string `json:"granteeRoleName,omitempty" tf:"grantee_role_name,omitempty"`

	// (String) Name of the user to grant privileges to.
	// Name of the `user` to grant privileges to.
	GranteeUserName *string `json:"granteeUserName,omitempty" tf:"grantee_user_name,omitempty"`

	// reference/statements/grant#privileges.
	// The privilege to grant, such as `CREATE DATABASE`, `SELECT`, etc. See https://clickhouse.com/docs/en/sql-reference/statements/grant#privileges.
	PrivilegeName *string `json:"privilegeName,omitempty" tf:"privilege_name,omitempty"`

	// (String) The name of the table to grant privilege on. Defaults to all tables if left null.
	// The name of the table to grant privilege on. Defaults to all tables if left null.
	TableName *string `json:"tableName,omitempty" tf:"table_name,omitempty"`
}

type GrantPrivilegeObservation struct {

	// scoped privileges, or a source name (e.g. S3) for source READ/WRITE grants. Supports a trailing * prefix pattern.
	// The object the privilege applies to: a user/role name for USER_NAME/DEFINER-scoped privileges, or a source name (e.g. `S3`) for source READ/WRITE grants. Supports a trailing `*` prefix pattern.
	AccessObject *string `json:"accessObject,omitempty" tf:"access_object,omitempty"`

	// (String) Name of the cluster to create the resource into. If omitted, resource will be created on the replica hit by the query.
	// This field must be left null when using a ClickHouse Cloud cluster.
	// When using a self hosted ClickHouse instance, this field should only be set when there is more than one replica and you are not using 'replicated' storage for user_directory.
	// Name of the cluster to create the resource into. If omitted, resource will be created on the replica hit by the query.
	// This field must be left null when using a ClickHouse Cloud cluster.
	// When using a self hosted ClickHouse instance, this field should only be set when there is more than one replica and you are not using 'replicated' storage for user_directory.
	ClusterName *string `json:"clusterName,omitempty" tf:"cluster_name,omitempty"`

	// (String) The name of the column in table_name to grant privilege on.
	// The name of the column in `table_name` to grant privilege on.
	ColumnName *string `json:"columnName,omitempty" tf:"column_name,omitempty"`

	// (Boolean) If true, emit GRANT CURRENT GRANTS(...) so the privilege is copied from the grantor's own grants instead of granted directly. Required on ClickHouse Cloud for broad privileges (e.g. ALL, or SELECT on *.*) that the admin user holds but cannot transfer directly. Note: the effective grants depend on what the grantor holds at apply time, so drift on a current_grants grant is not reconciled. On destroy the privilege is revoked in full from the grantee on the target.
	// If true, emit `GRANT CURRENT GRANTS(...)` so the privilege is copied from the grantor's own grants instead of granted directly. Required on ClickHouse Cloud for broad privileges (e.g. `ALL`, or `SELECT` on `*.*`) that the admin user holds but cannot transfer directly. Note: the effective grants depend on what the grantor holds at apply time, so drift on a `current_grants` grant is not reconciled. On destroy the privilege is revoked in full from the grantee on the target.
	CurrentGrants *bool `json:"currentGrants,omitempty" tf:"current_grants,omitempty"`

	// (String) The name of the database to grant privilege on. Defaults to all databases if left null
	// The name of the database to grant privilege on. Defaults to all databases if left null
	DatabaseName *string `json:"databaseName,omitempty" tf:"database_name,omitempty"`

	// (Boolean) If true, the grantee will be able to grant the same privileges to others.
	// If true, the grantee will be able to grant the same privileges to others.
	GrantOption *bool `json:"grantOption,omitempty" tf:"grant_option,omitempty"`

	// (String) Name of the role to grant privileges to.
	// Name of the `role` to grant privileges to.
	GranteeRoleName *string `json:"granteeRoleName,omitempty" tf:"grantee_role_name,omitempty"`

	// (String) Name of the user to grant privileges to.
	// Name of the `user` to grant privileges to.
	GranteeUserName *string `json:"granteeUserName,omitempty" tf:"grantee_user_name,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// reference/statements/grant#privileges.
	// The privilege to grant, such as `CREATE DATABASE`, `SELECT`, etc. See https://clickhouse.com/docs/en/sql-reference/statements/grant#privileges.
	PrivilegeName *string `json:"privilegeName,omitempty" tf:"privilege_name,omitempty"`

	// (String) The name of the table to grant privilege on. Defaults to all tables if left null.
	// The name of the table to grant privilege on. Defaults to all tables if left null.
	TableName *string `json:"tableName,omitempty" tf:"table_name,omitempty"`
}

type GrantPrivilegeParameters struct {

	// scoped privileges, or a source name (e.g. S3) for source READ/WRITE grants. Supports a trailing * prefix pattern.
	// The object the privilege applies to: a user/role name for USER_NAME/DEFINER-scoped privileges, or a source name (e.g. `S3`) for source READ/WRITE grants. Supports a trailing `*` prefix pattern.
	// +kubebuilder:validation:Optional
	AccessObject *string `json:"accessObject,omitempty" tf:"access_object,omitempty"`

	// (String) Name of the cluster to create the resource into. If omitted, resource will be created on the replica hit by the query.
	// This field must be left null when using a ClickHouse Cloud cluster.
	// When using a self hosted ClickHouse instance, this field should only be set when there is more than one replica and you are not using 'replicated' storage for user_directory.
	// Name of the cluster to create the resource into. If omitted, resource will be created on the replica hit by the query.
	// This field must be left null when using a ClickHouse Cloud cluster.
	// When using a self hosted ClickHouse instance, this field should only be set when there is more than one replica and you are not using 'replicated' storage for user_directory.
	// +kubebuilder:validation:Optional
	ClusterName *string `json:"clusterName,omitempty" tf:"cluster_name,omitempty"`

	// (String) The name of the column in table_name to grant privilege on.
	// The name of the column in `table_name` to grant privilege on.
	// +kubebuilder:validation:Optional
	ColumnName *string `json:"columnName,omitempty" tf:"column_name,omitempty"`

	// (Boolean) If true, emit GRANT CURRENT GRANTS(...) so the privilege is copied from the grantor's own grants instead of granted directly. Required on ClickHouse Cloud for broad privileges (e.g. ALL, or SELECT on *.*) that the admin user holds but cannot transfer directly. Note: the effective grants depend on what the grantor holds at apply time, so drift on a current_grants grant is not reconciled. On destroy the privilege is revoked in full from the grantee on the target.
	// If true, emit `GRANT CURRENT GRANTS(...)` so the privilege is copied from the grantor's own grants instead of granted directly. Required on ClickHouse Cloud for broad privileges (e.g. `ALL`, or `SELECT` on `*.*`) that the admin user holds but cannot transfer directly. Note: the effective grants depend on what the grantor holds at apply time, so drift on a `current_grants` grant is not reconciled. On destroy the privilege is revoked in full from the grantee on the target.
	// +kubebuilder:validation:Optional
	CurrentGrants *bool `json:"currentGrants,omitempty" tf:"current_grants,omitempty"`

	// (String) The name of the database to grant privilege on. Defaults to all databases if left null
	// The name of the database to grant privilege on. Defaults to all databases if left null
	// +kubebuilder:validation:Optional
	DatabaseName *string `json:"databaseName,omitempty" tf:"database_name,omitempty"`

	// (Boolean) If true, the grantee will be able to grant the same privileges to others.
	// If true, the grantee will be able to grant the same privileges to others.
	// +kubebuilder:validation:Optional
	GrantOption *bool `json:"grantOption,omitempty" tf:"grant_option,omitempty"`

	// (String) Name of the role to grant privileges to.
	// Name of the `role` to grant privileges to.
	// +kubebuilder:validation:Optional
	GranteeRoleName *string `json:"granteeRoleName,omitempty" tf:"grantee_role_name,omitempty"`

	// (String) Name of the user to grant privileges to.
	// Name of the `user` to grant privileges to.
	// +kubebuilder:validation:Optional
	GranteeUserName *string `json:"granteeUserName,omitempty" tf:"grantee_user_name,omitempty"`

	// reference/statements/grant#privileges.
	// The privilege to grant, such as `CREATE DATABASE`, `SELECT`, etc. See https://clickhouse.com/docs/en/sql-reference/statements/grant#privileges.
	// +kubebuilder:validation:Optional
	PrivilegeName *string `json:"privilegeName,omitempty" tf:"privilege_name,omitempty"`

	// (String) The name of the table to grant privilege on. Defaults to all tables if left null.
	// The name of the table to grant privilege on. Defaults to all tables if left null.
	// +kubebuilder:validation:Optional
	TableName *string `json:"tableName,omitempty" tf:"table_name,omitempty"`
}

// GrantPrivilegeSpec defines the desired state of GrantPrivilege
type GrantPrivilegeSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            GrantPrivilegeParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider GrantPrivilegeInitParameters `json:"initProvider,omitempty"`
}

// GrantPrivilegeStatus defines the observed state of GrantPrivilege.
type GrantPrivilegeStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               GrantPrivilegeObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// GrantPrivilege is the Schema for the GrantPrivileges API. You can use the clickhousedbops_grant_privilege resource to grant privileges on databases and tables to either a clickhousedbops_user or a clickhousedbops_role. Please note that in order to grant privileges to all database and/or all tables, the database and/or table fields must be set to null, and not to "*". Known limitations: On ClickHouse Cloud some broad privileges (for example ALL, or SELECT on
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,clickhousedbops}
type GrantPrivilege struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.privilegeName) || (has(self.initProvider) && has(self.initProvider.privilegeName))",message="spec.forProvider.privilegeName is a required parameter"
	Spec   GrantPrivilegeSpec   `json:"spec"`
	Status GrantPrivilegeStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// GrantPrivilegeList contains a list of GrantPrivileges
type GrantPrivilegeList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []GrantPrivilege `json:"items"`
}

// Repository type metadata.
var (
	GrantPrivilege_Kind             = "GrantPrivilege"
	GrantPrivilege_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: GrantPrivilege_Kind}.String()
	GrantPrivilege_KindAPIVersion   = GrantPrivilege_Kind + "." + CRDGroupVersion.String()
	GrantPrivilege_GroupVersionKind = CRDGroupVersion.WithKind(GrantPrivilege_Kind)
)

func init() {
	SchemeBuilder.Register(&GrantPrivilege{}, &GrantPrivilegeList{})
}
