// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type MaskingPolicyInitParameters struct {

	// : apply to all users and roles, excluding the ones listed. An empty set ([]) applies to everyone with no exclusions.
	// Apply the masking policy to all users and roles, excluding those listed. An empty set applies to everyone with no exclusions.
	// +listType=set
	GranteeAllExcept []*string `json:"granteeAllExcept,omitempty" tf:"grantee_all_except,omitempty"`

	// : a list of user and role names. ClickHouse stores these as one untyped list and resolves each name to a user before a role, so users and roles are not distinguished here.
	// Set of user or role names the masking policy applies to. ClickHouse resolves each name to a user before a role, so users and roles are not distinguished here.
	// +listType=set
	GranteeNames []*string `json:"granteeNames,omitempty" tf:"grantee_names,omitempty"`

	// (Map of String) Map of column name to the ClickHouse expression that replaces it (the UPDATE column = expression clause). The expression is interpolated verbatim, e.g. '** redacted **' or concat(splitByChar('.', clientIp)[1], '.x.x').
	// Map of column name to the ClickHouse expression that replaces it (the `UPDATE column = expression` clause). The expression is interpolated verbatim, e.g. `'** redacted **'` or `concat(splitByChar('.', clientIp)[1], '.x.x')`.
	// +mapType=granular
	Masks map[string]*string `json:"masks,omitempty" tf:"masks,omitempty"`

	// negative. Defaults to 0.
	// Optional priority. When several policies touch the same column, they are applied from highest to lowest priority. Must be non-negative. Defaults to 0.
	Priority *float64 `json:"priority,omitempty" tf:"priority,omitempty"`

	// (String) Optional WHERE condition; the columns are only masked for rows matching it. For example ownerId NOT IN ('team_a', 'team_b').
	// Optional `WHERE` condition; the columns are only masked for rows matching it. For example `ownerId NOT IN ('team_a', 'team_b')`.
	WhereExpression *string `json:"whereExpression,omitempty" tf:"where_expression,omitempty"`
}

type MaskingPolicyObservation struct {

	// (String) The database of the table the masking policy applies to. Must be a concrete name; wildcards (*) are not supported.
	// The database of the table the masking policy applies to. Must be a concrete name; wildcards (`*`) are not supported.
	DatabaseName *string `json:"databaseName,omitempty" tf:"database_name,omitempty"`

	// : apply to all users and roles, excluding the ones listed. An empty set ([]) applies to everyone with no exclusions.
	// Apply the masking policy to all users and roles, excluding those listed. An empty set applies to everyone with no exclusions.
	// +listType=set
	GranteeAllExcept []*string `json:"granteeAllExcept,omitempty" tf:"grantee_all_except,omitempty"`

	// : a list of user and role names. ClickHouse stores these as one untyped list and resolves each name to a user before a role, so users and roles are not distinguished here.
	// Set of user or role names the masking policy applies to. ClickHouse resolves each name to a user before a role, so users and roles are not distinguished here.
	// +listType=set
	GranteeNames []*string `json:"granteeNames,omitempty" tf:"grantee_names,omitempty"`

	// assigned ID for the masking policy.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Map of String) Map of column name to the ClickHouse expression that replaces it (the UPDATE column = expression clause). The expression is interpolated verbatim, e.g. '** redacted **' or concat(splitByChar('.', clientIp)[1], '.x.x').
	// Map of column name to the ClickHouse expression that replaces it (the `UPDATE column = expression` clause). The expression is interpolated verbatim, e.g. `'** redacted **'` or `concat(splitByChar('.', clientIp)[1], '.x.x')`.
	// +mapType=granular
	Masks map[string]*string `json:"masks,omitempty" tf:"masks,omitempty"`

	// negative. Defaults to 0.
	// Optional priority. When several policies touch the same column, they are applied from highest to lowest priority. Must be non-negative. Defaults to 0.
	Priority *float64 `json:"priority,omitempty" tf:"priority,omitempty"`

	// (String) The table the masking policy applies to. Must be a concrete name; wildcards (*) are not supported.
	// The table the masking policy applies to. Must be a concrete name; wildcards (`*`) are not supported.
	TableName *string `json:"tableName,omitempty" tf:"table_name,omitempty"`

	// (String) Optional WHERE condition; the columns are only masked for rows matching it. For example ownerId NOT IN ('team_a', 'team_b').
	// Optional `WHERE` condition; the columns are only masked for rows matching it. For example `ownerId NOT IN ('team_a', 'team_b')`.
	WhereExpression *string `json:"whereExpression,omitempty" tf:"where_expression,omitempty"`
}

type MaskingPolicyParameters struct {

	// (String) The database of the table the masking policy applies to. Must be a concrete name; wildcards (*) are not supported.
	// The database of the table the masking policy applies to. Must be a concrete name; wildcards (`*`) are not supported.
	// +crossplane:generate:reference:type=github.com/lansweeper-oss/provider-clickhousedbops/apis/namespaced/clickhousedbops/v1alpha1.Database
	// +kubebuilder:validation:Optional
	DatabaseName *string `json:"databaseName,omitempty" tf:"database_name,omitempty"`

	// Reference to a Database in clickhousedbops to populate databaseName.
	// +kubebuilder:validation:Optional
	DatabaseNameRef *v2.NamespacedReference `json:"databaseNameRef,omitempty" tf:"-"`

	// Selector for a Database in clickhousedbops to populate databaseName.
	// +kubebuilder:validation:Optional
	DatabaseNameSelector *v2.NamespacedSelector `json:"databaseNameSelector,omitempty" tf:"-"`

	// : apply to all users and roles, excluding the ones listed. An empty set ([]) applies to everyone with no exclusions.
	// Apply the masking policy to all users and roles, excluding those listed. An empty set applies to everyone with no exclusions.
	// +kubebuilder:validation:Optional
	// +listType=set
	GranteeAllExcept []*string `json:"granteeAllExcept,omitempty" tf:"grantee_all_except,omitempty"`

	// : a list of user and role names. ClickHouse stores these as one untyped list and resolves each name to a user before a role, so users and roles are not distinguished here.
	// Set of user or role names the masking policy applies to. ClickHouse resolves each name to a user before a role, so users and roles are not distinguished here.
	// +kubebuilder:validation:Optional
	// +listType=set
	GranteeNames []*string `json:"granteeNames,omitempty" tf:"grantee_names,omitempty"`

	// (Map of String) Map of column name to the ClickHouse expression that replaces it (the UPDATE column = expression clause). The expression is interpolated verbatim, e.g. '** redacted **' or concat(splitByChar('.', clientIp)[1], '.x.x').
	// Map of column name to the ClickHouse expression that replaces it (the `UPDATE column = expression` clause). The expression is interpolated verbatim, e.g. `'** redacted **'` or `concat(splitByChar('.', clientIp)[1], '.x.x')`.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Masks map[string]*string `json:"masks,omitempty" tf:"masks,omitempty"`

	// negative. Defaults to 0.
	// Optional priority. When several policies touch the same column, they are applied from highest to lowest priority. Must be non-negative. Defaults to 0.
	// +kubebuilder:validation:Optional
	Priority *float64 `json:"priority,omitempty" tf:"priority,omitempty"`

	// (String) The table the masking policy applies to. Must be a concrete name; wildcards (*) are not supported.
	// The table the masking policy applies to. Must be a concrete name; wildcards (`*`) are not supported.
	// +kubebuilder:validation:Required
	TableName *string `json:"tableName" tf:"table_name,omitempty"`

	// (String) Optional WHERE condition; the columns are only masked for rows matching it. For example ownerId NOT IN ('team_a', 'team_b').
	// Optional `WHERE` condition; the columns are only masked for rows matching it. For example `ownerId NOT IN ('team_a', 'team_b')`.
	// +kubebuilder:validation:Optional
	WhereExpression *string `json:"whereExpression,omitempty" tf:"where_expression,omitempty"`
}

// MaskingPolicySpec defines the desired state of MaskingPolicy
type MaskingPolicySpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            MaskingPolicyParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider MaskingPolicyInitParameters `json:"initProvider,omitempty"`
}

// MaskingPolicyStatus defines the observed state of MaskingPolicy.
type MaskingPolicyStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               MaskingPolicyObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// MaskingPolicy is the Schema for the MaskingPolicys API. You can use the clickhousedbops_masking_policy resource to manage a masking policy https://clickhouse.com/docs/cloud/guides/data-masking on a ClickHouse table. A masking policy rewrites the listed columns for the grantees named in the policy, optionally only for the rows matching where_expression. Use it to hide PII or secrets from a role while leaving the underlying data untouched. ~> ClickHouse Cloud only: masking policies are only available on ClickHouse Cloud (version 25.12+) and the feature must be enabled for the service. Open-source ClickHouse rejects the DDL. Resource can be imported by id or the
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,clickhousedbops}
type MaskingPolicy struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.masks) || (has(self.initProvider) && has(self.initProvider.masks))",message="spec.forProvider.masks is a required parameter"
	Spec   MaskingPolicySpec   `json:"spec"`
	Status MaskingPolicyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// MaskingPolicyList contains a list of MaskingPolicys
type MaskingPolicyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []MaskingPolicy `json:"items"`
}

// Repository type metadata.
var (
	MaskingPolicy_Kind             = "MaskingPolicy"
	MaskingPolicy_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: MaskingPolicy_Kind}.String()
	MaskingPolicy_KindAPIVersion   = MaskingPolicy_Kind + "." + CRDGroupVersion.String()
	MaskingPolicy_GroupVersionKind = CRDGroupVersion.WithKind(MaskingPolicy_Kind)
)

func init() {
	SchemeBuilder.Register(&MaskingPolicy{}, &MaskingPolicyList{})
}
