// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type GrantPrivilegeInitParameters struct {

	// Name of the cluster to create the resource into. If omitted, resource will be created on the replica hit by the query.
	// This field must be left null when using a ClickHouse Cloud cluster.
	// When using a self hosted ClickHouse instance, this field should only be set when there is more than one replica and you are not using 'replicated' storage for user_directory.
	ClusterName *string `json:"clusterName,omitempty" tf:"cluster_name,omitempty"`

	// The name of the column in `table_name` to grant privilege on.
	ColumnName *string `json:"columnName,omitempty" tf:"column_name,omitempty"`

	// The name of the database to grant privilege on. Defaults to all databases if left null
	DatabaseName *string `json:"databaseName,omitempty" tf:"database_name,omitempty"`

	// If true, the grantee will be able to grant the same privileges to others.
	GrantOption *bool `json:"grantOption,omitempty" tf:"grant_option,omitempty"`

	// Name of the `role` to grant privileges to.
	GranteeRoleName *string `json:"granteeRoleName,omitempty" tf:"grantee_role_name,omitempty"`

	// Name of the `user` to grant privileges to.
	GranteeUserName *string `json:"granteeUserName,omitempty" tf:"grantee_user_name,omitempty"`

	// The privilege to grant, such as `CREATE DATABASE`, `SELECT`, etc. See https://clickhouse.com/docs/en/sql-reference/statements/grant#privileges.
	PrivilegeName *string `json:"privilegeName,omitempty" tf:"privilege_name,omitempty"`

	// The name of the table to grant privilege on.
	TableName *string `json:"tableName,omitempty" tf:"table_name,omitempty"`
}

type GrantPrivilegeObservation struct {

	// Name of the cluster to create the resource into. If omitted, resource will be created on the replica hit by the query.
	// This field must be left null when using a ClickHouse Cloud cluster.
	// When using a self hosted ClickHouse instance, this field should only be set when there is more than one replica and you are not using 'replicated' storage for user_directory.
	ClusterName *string `json:"clusterName,omitempty" tf:"cluster_name,omitempty"`

	// The name of the column in `table_name` to grant privilege on.
	ColumnName *string `json:"columnName,omitempty" tf:"column_name,omitempty"`

	// The name of the database to grant privilege on. Defaults to all databases if left null
	DatabaseName *string `json:"databaseName,omitempty" tf:"database_name,omitempty"`

	// If true, the grantee will be able to grant the same privileges to others.
	GrantOption *bool `json:"grantOption,omitempty" tf:"grant_option,omitempty"`

	// Name of the `role` to grant privileges to.
	GranteeRoleName *string `json:"granteeRoleName,omitempty" tf:"grantee_role_name,omitempty"`

	// Name of the `user` to grant privileges to.
	GranteeUserName *string `json:"granteeUserName,omitempty" tf:"grantee_user_name,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The privilege to grant, such as `CREATE DATABASE`, `SELECT`, etc. See https://clickhouse.com/docs/en/sql-reference/statements/grant#privileges.
	PrivilegeName *string `json:"privilegeName,omitempty" tf:"privilege_name,omitempty"`

	// The name of the table to grant privilege on.
	TableName *string `json:"tableName,omitempty" tf:"table_name,omitempty"`
}

type GrantPrivilegeParameters struct {

	// Name of the cluster to create the resource into. If omitted, resource will be created on the replica hit by the query.
	// This field must be left null when using a ClickHouse Cloud cluster.
	// When using a self hosted ClickHouse instance, this field should only be set when there is more than one replica and you are not using 'replicated' storage for user_directory.
	// +kubebuilder:validation:Optional
	ClusterName *string `json:"clusterName,omitempty" tf:"cluster_name,omitempty"`

	// The name of the column in `table_name` to grant privilege on.
	// +kubebuilder:validation:Optional
	ColumnName *string `json:"columnName,omitempty" tf:"column_name,omitempty"`

	// The name of the database to grant privilege on. Defaults to all databases if left null
	// +kubebuilder:validation:Optional
	DatabaseName *string `json:"databaseName,omitempty" tf:"database_name,omitempty"`

	// If true, the grantee will be able to grant the same privileges to others.
	// +kubebuilder:validation:Optional
	GrantOption *bool `json:"grantOption,omitempty" tf:"grant_option,omitempty"`

	// Name of the `role` to grant privileges to.
	// +kubebuilder:validation:Optional
	GranteeRoleName *string `json:"granteeRoleName,omitempty" tf:"grantee_role_name,omitempty"`

	// Name of the `user` to grant privileges to.
	// +kubebuilder:validation:Optional
	GranteeUserName *string `json:"granteeUserName,omitempty" tf:"grantee_user_name,omitempty"`

	// The privilege to grant, such as `CREATE DATABASE`, `SELECT`, etc. See https://clickhouse.com/docs/en/sql-reference/statements/grant#privileges.
	// +kubebuilder:validation:Optional
	PrivilegeName *string `json:"privilegeName,omitempty" tf:"privilege_name,omitempty"`

	// The name of the table to grant privilege on.
	// +kubebuilder:validation:Optional
	TableName *string `json:"tableName,omitempty" tf:"table_name,omitempty"`
}

// GrantPrivilegeSpec defines the desired state of GrantPrivilege
type GrantPrivilegeSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     GrantPrivilegeParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider GrantPrivilegeInitParameters `json:"initProvider,omitempty"`
}

// GrantPrivilegeStatus defines the observed state of GrantPrivilege.
type GrantPrivilegeStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        GrantPrivilegeObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// GrantPrivilege is the Schema for the GrantPrivileges API. You can use the clickhousedbops_grant_privilege resource to grant privileges on databases and tables to either a clickhousedbops_user or a clickhousedbops_role. Please note that in order to grant privileges to all database and/or all tables, the database and/or table fields must be set to null, and not to "*". Known limitations: Only a subset of privileges can be granted on ClickHouse cloud. For example the ALL privilege can't be granted. See https://clickhouse.com/docs/en/sql-reference/statements/grant#allIt's not possible to grant privileges using their alias name. The canonical name must be used.It's not possible to grant group of privileges. Please grant each member of the group individually instead.It's not possible to grant the same clickhousedbops_grant_privilege to both a clickhousedbops_user and a clickhousedbops_role using a single clickhousedbops_grant_privilege stanza. You can do that using two different stanzas, one with grantee_user_name and the other with grantee_role_name fields set.It's not possible to grant the same privilege (example 'SELECT') to multiple entities (for example tables) with a single stanza. You can do that my creating one stanza for each entity you want to grant privileges on.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,clickhousedbops}
type GrantPrivilege struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.privilegeName) || (has(self.initProvider) && has(self.initProvider.privilegeName))",message="spec.forProvider.privilegeName is a required parameter"
	Spec   GrantPrivilegeSpec   `json:"spec"`
	Status GrantPrivilegeStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// GrantPrivilegeList contains a list of GrantPrivileges
type GrantPrivilegeList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []GrantPrivilege `json:"items"`
}

// Repository type metadata.
var (
	GrantPrivilege_Kind             = "GrantPrivilege"
	GrantPrivilege_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: GrantPrivilege_Kind}.String()
	GrantPrivilege_KindAPIVersion   = GrantPrivilege_Kind + "." + CRDGroupVersion.String()
	GrantPrivilege_GroupVersionKind = CRDGroupVersion.WithKind(GrantPrivilege_Kind)
)

func init() {
	SchemeBuilder.Register(&GrantPrivilege{}, &GrantPrivilegeList{})
}
