// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type SettingProfileInitParameters struct {

	// Name of the cluster to create the resource into. If omitted, resource will be created on the replica hit by the query.
	// This field must be left null when using a ClickHouse Cloud cluster.
	// When using a self hosted ClickHouse instance, this field should only be set when there is more than one replica and you are not using 'replicated' storage for user_directory.
	ClusterName *string `json:"clusterName,omitempty" tf:"cluster_name,omitempty"`

	// List of setting profile names to inherit from
	InheritFrom []*string `json:"inheritFrom,omitempty" tf:"inherit_from,omitempty"`

	// Name of the settings profile
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type SettingProfileObservation struct {

	// Name of the cluster to create the resource into. If omitted, resource will be created on the replica hit by the query.
	// This field must be left null when using a ClickHouse Cloud cluster.
	// When using a self hosted ClickHouse instance, this field should only be set when there is more than one replica and you are not using 'replicated' storage for user_directory.
	ClusterName *string `json:"clusterName,omitempty" tf:"cluster_name,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// List of setting profile names to inherit from
	InheritFrom []*string `json:"inheritFrom,omitempty" tf:"inherit_from,omitempty"`

	// Name of the settings profile
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type SettingProfileParameters struct {

	// Name of the cluster to create the resource into. If omitted, resource will be created on the replica hit by the query.
	// This field must be left null when using a ClickHouse Cloud cluster.
	// When using a self hosted ClickHouse instance, this field should only be set when there is more than one replica and you are not using 'replicated' storage for user_directory.
	// +kubebuilder:validation:Optional
	ClusterName *string `json:"clusterName,omitempty" tf:"cluster_name,omitempty"`

	// List of setting profile names to inherit from
	// +kubebuilder:validation:Optional
	InheritFrom []*string `json:"inheritFrom,omitempty" tf:"inherit_from,omitempty"`

	// Name of the settings profile
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

// SettingProfileSpec defines the desired state of SettingProfile
type SettingProfileSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     SettingProfileParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SettingProfileInitParameters `json:"initProvider,omitempty"`
}

// SettingProfileStatus defines the observed state of SettingProfile.
type SettingProfileStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        SettingProfileObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// SettingProfile is the Schema for the SettingProfiles API. You can use the clickhousedbops_settings_profile resource to create a Setting Profile in a ClickHouse instance.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,clickhousedbops}
type SettingProfile struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   SettingProfileSpec   `json:"spec"`
	Status SettingProfileStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SettingProfileList contains a list of SettingProfiles
type SettingProfileList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SettingProfile `json:"items"`
}

// Repository type metadata.
var (
	SettingProfile_Kind             = "SettingProfile"
	SettingProfile_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: SettingProfile_Kind}.String()
	SettingProfile_KindAPIVersion   = SettingProfile_Kind + "." + CRDGroupVersion.String()
	SettingProfile_GroupVersionKind = CRDGroupVersion.WithKind(SettingProfile_Kind)
)

func init() {
	SchemeBuilder.Register(&SettingProfile{}, &SettingProfileList{})
}
