// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type SettingProfileAssociationInitParameters struct {

	// (String) Name of the cluster to create the resource into. If omitted, resource will be created on the replica hit by the query.
	// This field must be left null when using a ClickHouse Cloud cluster.
	// When using a self hosted ClickHouse instance, this field should only be set when there is more than one replica and you are not using 'replicated' storage for user_directory.
	// Name of the cluster to create the resource into. If omitted, resource will be created on the replica hit by the query.
	// This field must be left null when using a ClickHouse Cloud cluster.
	// When using a self hosted ClickHouse instance, this field should only be set when there is more than one replica and you are not using 'replicated' storage for user_directory.
	ClusterName *string `json:"clusterName,omitempty" tf:"cluster_name,omitempty"`

	// (String) ID of the SettingsProfileAssociation to associate the Settings profile to
	// ID of the SettingsProfileAssociation to associate the Settings profile to
	RoleID *string `json:"roleId,omitempty" tf:"role_id,omitempty"`

	// (String) ID of the settings profile to associate
	// ID of the settings profile to associate
	SettingsProfileID *string `json:"settingsProfileId,omitempty" tf:"settings_profile_id,omitempty"`

	// (String) ID of the User to associate the Settings profile to
	// ID of the User to associate the Settings profile to
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`
}

type SettingProfileAssociationObservation struct {

	// (String) Name of the cluster to create the resource into. If omitted, resource will be created on the replica hit by the query.
	// This field must be left null when using a ClickHouse Cloud cluster.
	// When using a self hosted ClickHouse instance, this field should only be set when there is more than one replica and you are not using 'replicated' storage for user_directory.
	// Name of the cluster to create the resource into. If omitted, resource will be created on the replica hit by the query.
	// This field must be left null when using a ClickHouse Cloud cluster.
	// When using a self hosted ClickHouse instance, this field should only be set when there is more than one replica and you are not using 'replicated' storage for user_directory.
	ClusterName *string `json:"clusterName,omitempty" tf:"cluster_name,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) ID of the SettingsProfileAssociation to associate the Settings profile to
	// ID of the SettingsProfileAssociation to associate the Settings profile to
	RoleID *string `json:"roleId,omitempty" tf:"role_id,omitempty"`

	// (String) ID of the settings profile to associate
	// ID of the settings profile to associate
	SettingsProfileID *string `json:"settingsProfileId,omitempty" tf:"settings_profile_id,omitempty"`

	// (String) ID of the User to associate the Settings profile to
	// ID of the User to associate the Settings profile to
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`
}

type SettingProfileAssociationParameters struct {

	// (String) Name of the cluster to create the resource into. If omitted, resource will be created on the replica hit by the query.
	// This field must be left null when using a ClickHouse Cloud cluster.
	// When using a self hosted ClickHouse instance, this field should only be set when there is more than one replica and you are not using 'replicated' storage for user_directory.
	// Name of the cluster to create the resource into. If omitted, resource will be created on the replica hit by the query.
	// This field must be left null when using a ClickHouse Cloud cluster.
	// When using a self hosted ClickHouse instance, this field should only be set when there is more than one replica and you are not using 'replicated' storage for user_directory.
	// +kubebuilder:validation:Optional
	ClusterName *string `json:"clusterName,omitempty" tf:"cluster_name,omitempty"`

	// (String) ID of the SettingsProfileAssociation to associate the Settings profile to
	// ID of the SettingsProfileAssociation to associate the Settings profile to
	// +kubebuilder:validation:Optional
	RoleID *string `json:"roleId,omitempty" tf:"role_id,omitempty"`

	// (String) ID of the settings profile to associate
	// ID of the settings profile to associate
	// +kubebuilder:validation:Optional
	SettingsProfileID *string `json:"settingsProfileId,omitempty" tf:"settings_profile_id,omitempty"`

	// (String) ID of the User to associate the Settings profile to
	// ID of the User to associate the Settings profile to
	// +kubebuilder:validation:Optional
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`
}

// SettingProfileAssociationSpec defines the desired state of SettingProfileAssociation
type SettingProfileAssociationSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     SettingProfileAssociationParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SettingProfileAssociationInitParameters `json:"initProvider,omitempty"`
}

// SettingProfileAssociationStatus defines the observed state of SettingProfileAssociation.
type SettingProfileAssociationStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        SettingProfileAssociationObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// SettingProfileAssociation is the Schema for the SettingProfileAssociations API. You can use the clickhousedbops_settings_profile_association resource to associate a settings_profile to a role or user in a ClickHouse instance.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,clickhousedbops}
type SettingProfileAssociation struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.settingsProfileId) || (has(self.initProvider) && has(self.initProvider.settingsProfileId))",message="spec.forProvider.settingsProfileId is a required parameter"
	Spec   SettingProfileAssociationSpec   `json:"spec"`
	Status SettingProfileAssociationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SettingProfileAssociationList contains a list of SettingProfileAssociations
type SettingProfileAssociationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SettingProfileAssociation `json:"items"`
}

// Repository type metadata.
var (
	SettingProfileAssociation_Kind             = "SettingProfileAssociation"
	SettingProfileAssociation_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: SettingProfileAssociation_Kind}.String()
	SettingProfileAssociation_KindAPIVersion   = SettingProfileAssociation_Kind + "." + CRDGroupVersion.String()
	SettingProfileAssociation_GroupVersionKind = CRDGroupVersion.WithKind(SettingProfileAssociation_Kind)
)

func init() {
	SchemeBuilder.Register(&SettingProfileAssociation{}, &SettingProfileAssociationList{})
}
