// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type AuthInitParameters struct {

	// (Block List) Bcrypt hash authentication. (see below for nested schema)
	// Bcrypt hash authentication.
	BcryptHash []BcryptHashInitParameters `json:"bcryptHash,omitempty" tf:"bcrypt_hash,omitempty"`

	// (Block List) Bcrypt password authentication. (see below for nested schema)
	// Bcrypt password authentication.
	BcryptPassword []BcryptPasswordInitParameters `json:"bcryptPassword,omitempty" tf:"bcrypt_password,omitempty"`

	// (Block List) Double SHA1 hash authentication. (see below for nested schema)
	// Double SHA1 hash authentication.
	DoubleSha1Hash []DoubleSha1HashInitParameters `json:"doubleSha1Hash,omitempty" tf:"double_sha1_hash,omitempty"`

	// (Block List) Double SHA1 password authentication. (see below for nested schema)
	// Double SHA1 password authentication.
	DoubleSha1Password []DoubleSha1PasswordInitParameters `json:"doubleSha1Password,omitempty" tf:"double_sha1_password,omitempty"`

	// (Block List) HTTP authentication. Exactly one of server or scheme. (see below for nested schema)
	// HTTP authentication. Exactly one of server or scheme.
	HTTP []HTTPInitParameters `json:"http,omitempty" tf:"http,omitempty"`

	// (Block List) Kerberos authentication. (see below for nested schema)
	// Kerberos authentication.
	Kerberos []KerberosInitParameters `json:"kerberos,omitempty" tf:"kerberos,omitempty"`

	// (Block List) LDAP authentication. (see below for nested schema)
	// LDAP authentication.
	Ldap []LdapInitParameters `json:"ldap,omitempty" tf:"ldap,omitempty"`

	// is exclusive — it cannot be combined with any other method.
	// Passwordless authentication. Cannot be combined with any other method.
	NoPassword []NoPasswordInitParameters `json:"noPassword,omitempty" tf:"no_password,omitempty"`

	// (Block List) Plaintext password authentication. (see below for nested schema)
	// Plaintext password authentication.
	PlaintextPassword []PlaintextPasswordInitParameters `json:"plaintextPassword,omitempty" tf:"plaintext_password,omitempty"`

	// (Block List) SSH key authentication. (see below for nested schema)
	// SSH key authentication.
	SSHKey []SSHKeyInitParameters `json:"sshKey,omitempty" tf:"ssh_key,omitempty"`

	// (Block List) SSL certificate authentication. Exactly one of common_name or subject_alt_name. (see below for nested schema)
	// SSL certificate authentication. Exactly one of common_name or subject_alt_name.
	SSLCertificate []SSLCertificateInitParameters `json:"sslCertificate,omitempty" tf:"ssl_certificate,omitempty"`

	// (Block List) SHA256 hash authentication. (see below for nested schema)
	// SHA256 hash authentication.
	Sha256Hash []Sha256HashInitParameters `json:"sha256Hash,omitempty" tf:"sha256_hash,omitempty"`

	// (Block List) SHA256 password authentication (ClickHouse computes the hash). (see below for nested schema)
	// SHA256 password authentication (ClickHouse computes the hash).
	Sha256Password []Sha256PasswordInitParameters `json:"sha256Password,omitempty" tf:"sha256_password,omitempty"`
}

type AuthObservation struct {

	// (Block List) Bcrypt hash authentication. (see below for nested schema)
	// Bcrypt hash authentication.
	BcryptHash []BcryptHashObservation `json:"bcryptHash,omitempty" tf:"bcrypt_hash,omitempty"`

	// (Block List) Bcrypt password authentication. (see below for nested schema)
	// Bcrypt password authentication.
	BcryptPassword []BcryptPasswordObservation `json:"bcryptPassword,omitempty" tf:"bcrypt_password,omitempty"`

	// (Block List) Double SHA1 hash authentication. (see below for nested schema)
	// Double SHA1 hash authentication.
	DoubleSha1Hash []DoubleSha1HashObservation `json:"doubleSha1Hash,omitempty" tf:"double_sha1_hash,omitempty"`

	// (Block List) Double SHA1 password authentication. (see below for nested schema)
	// Double SHA1 password authentication.
	DoubleSha1Password []DoubleSha1PasswordObservation `json:"doubleSha1Password,omitempty" tf:"double_sha1_password,omitempty"`

	// (Block List) HTTP authentication. Exactly one of server or scheme. (see below for nested schema)
	// HTTP authentication. Exactly one of server or scheme.
	HTTP []HTTPObservation `json:"http,omitempty" tf:"http,omitempty"`

	// (Block List) Kerberos authentication. (see below for nested schema)
	// Kerberos authentication.
	Kerberos []KerberosObservation `json:"kerberos,omitempty" tf:"kerberos,omitempty"`

	// (Block List) LDAP authentication. (see below for nested schema)
	// LDAP authentication.
	Ldap []LdapObservation `json:"ldap,omitempty" tf:"ldap,omitempty"`

	// is exclusive — it cannot be combined with any other method.
	// Passwordless authentication. Cannot be combined with any other method.
	NoPassword []NoPasswordParameters `json:"noPassword,omitempty" tf:"no_password,omitempty"`

	// (Block List) Plaintext password authentication. (see below for nested schema)
	// Plaintext password authentication.
	PlaintextPassword []PlaintextPasswordObservation `json:"plaintextPassword,omitempty" tf:"plaintext_password,omitempty"`

	// (Block List) SSH key authentication. (see below for nested schema)
	// SSH key authentication.
	SSHKey []SSHKeyObservation `json:"sshKey,omitempty" tf:"ssh_key,omitempty"`

	// (Block List) SSL certificate authentication. Exactly one of common_name or subject_alt_name. (see below for nested schema)
	// SSL certificate authentication. Exactly one of common_name or subject_alt_name.
	SSLCertificate []SSLCertificateObservation `json:"sslCertificate,omitempty" tf:"ssl_certificate,omitempty"`

	// (Block List) SHA256 hash authentication. (see below for nested schema)
	// SHA256 hash authentication.
	Sha256Hash []Sha256HashObservation `json:"sha256Hash,omitempty" tf:"sha256_hash,omitempty"`

	// (Block List) SHA256 password authentication (ClickHouse computes the hash). (see below for nested schema)
	// SHA256 password authentication (ClickHouse computes the hash).
	Sha256Password []Sha256PasswordObservation `json:"sha256Password,omitempty" tf:"sha256_password,omitempty"`
}

type AuthParameters struct {

	// (Block List) Bcrypt hash authentication. (see below for nested schema)
	// Bcrypt hash authentication.
	// +kubebuilder:validation:Optional
	BcryptHash []BcryptHashParameters `json:"bcryptHash,omitempty" tf:"bcrypt_hash,omitempty"`

	// (Block List) Bcrypt password authentication. (see below for nested schema)
	// Bcrypt password authentication.
	// +kubebuilder:validation:Optional
	BcryptPassword []BcryptPasswordParameters `json:"bcryptPassword,omitempty" tf:"bcrypt_password,omitempty"`

	// (Block List) Double SHA1 hash authentication. (see below for nested schema)
	// Double SHA1 hash authentication.
	// +kubebuilder:validation:Optional
	DoubleSha1Hash []DoubleSha1HashParameters `json:"doubleSha1Hash,omitempty" tf:"double_sha1_hash,omitempty"`

	// (Block List) Double SHA1 password authentication. (see below for nested schema)
	// Double SHA1 password authentication.
	// +kubebuilder:validation:Optional
	DoubleSha1Password []DoubleSha1PasswordParameters `json:"doubleSha1Password,omitempty" tf:"double_sha1_password,omitempty"`

	// (Block List) HTTP authentication. Exactly one of server or scheme. (see below for nested schema)
	// HTTP authentication. Exactly one of server or scheme.
	// +kubebuilder:validation:Optional
	HTTP []HTTPParameters `json:"http,omitempty" tf:"http,omitempty"`

	// (Block List) Kerberos authentication. (see below for nested schema)
	// Kerberos authentication.
	// +kubebuilder:validation:Optional
	Kerberos []KerberosParameters `json:"kerberos,omitempty" tf:"kerberos,omitempty"`

	// (Block List) LDAP authentication. (see below for nested schema)
	// LDAP authentication.
	// +kubebuilder:validation:Optional
	Ldap []LdapParameters `json:"ldap,omitempty" tf:"ldap,omitempty"`

	// is exclusive — it cannot be combined with any other method.
	// Passwordless authentication. Cannot be combined with any other method.
	// +kubebuilder:validation:Optional
	NoPassword []NoPasswordParameters `json:"noPassword,omitempty" tf:"no_password,omitempty"`

	// (Block List) Plaintext password authentication. (see below for nested schema)
	// Plaintext password authentication.
	// +kubebuilder:validation:Optional
	PlaintextPassword []PlaintextPasswordParameters `json:"plaintextPassword,omitempty" tf:"plaintext_password,omitempty"`

	// (Block List) SSH key authentication. (see below for nested schema)
	// SSH key authentication.
	// +kubebuilder:validation:Optional
	SSHKey []SSHKeyParameters `json:"sshKey,omitempty" tf:"ssh_key,omitempty"`

	// (Block List) SSL certificate authentication. Exactly one of common_name or subject_alt_name. (see below for nested schema)
	// SSL certificate authentication. Exactly one of common_name or subject_alt_name.
	// +kubebuilder:validation:Optional
	SSLCertificate []SSLCertificateParameters `json:"sslCertificate,omitempty" tf:"ssl_certificate,omitempty"`

	// (Block List) SHA256 hash authentication. (see below for nested schema)
	// SHA256 hash authentication.
	// +kubebuilder:validation:Optional
	Sha256Hash []Sha256HashParameters `json:"sha256Hash,omitempty" tf:"sha256_hash,omitempty"`

	// (Block List) SHA256 password authentication (ClickHouse computes the hash). (see below for nested schema)
	// SHA256 password authentication (ClickHouse computes the hash).
	// +kubebuilder:validation:Optional
	Sha256Password []Sha256PasswordParameters `json:"sha256Password,omitempty" tf:"sha256_password,omitempty"`
}

type BcryptHashInitParameters struct {

	// 11.
	// Authentication value stored in state.11. Exactly one of value or value_wo.
	ValueSecretRef *v2.SecretKeySelector `json:"valueSecretRef,omitempty" tf:"-"`

	// 11).
	// Bump value_wo_version to re-apply the value.
	// Write-only authentication value, not stored in state.11.
	ValueWoSecretRef *v2.SecretKeySelector `json:"valueWoSecretRef,omitempty" tf:"-"`

	// apply the write-only value.
	// Version of value_wo. Bump to re-apply the write-only value.
	ValueWoVersion *float64 `json:"valueWoVersion,omitempty" tf:"value_wo_version,omitempty"`
}

type BcryptHashObservation struct {

	// apply the write-only value.
	// Version of value_wo. Bump to re-apply the write-only value.
	ValueWoVersion *float64 `json:"valueWoVersion,omitempty" tf:"value_wo_version,omitempty"`
}

type BcryptHashParameters struct {

	// 11.
	// Authentication value stored in state.11. Exactly one of value or value_wo.
	// +kubebuilder:validation:Optional
	ValueSecretRef *v2.SecretKeySelector `json:"valueSecretRef,omitempty" tf:"-"`

	// 11).
	// Bump value_wo_version to re-apply the value.
	// Write-only authentication value, not stored in state.11.
	// +kubebuilder:validation:Optional
	ValueWoSecretRef *v2.SecretKeySelector `json:"valueWoSecretRef,omitempty" tf:"-"`

	// apply the write-only value.
	// Version of value_wo. Bump to re-apply the write-only value.
	// +kubebuilder:validation:Optional
	ValueWoVersion *float64 `json:"valueWoVersion,omitempty" tf:"value_wo_version,omitempty"`
}

type BcryptPasswordInitParameters struct {

	// 11.
	// Authentication value stored in state.11. Exactly one of value or value_wo.
	ValueSecretRef *v2.SecretKeySelector `json:"valueSecretRef,omitempty" tf:"-"`

	// 11).
	// Bump value_wo_version to re-apply the value.
	// Write-only authentication value, not stored in state.11.
	ValueWoSecretRef *v2.SecretKeySelector `json:"valueWoSecretRef,omitempty" tf:"-"`

	// apply the write-only value.
	// Version of value_wo. Bump to re-apply the write-only value.
	ValueWoVersion *float64 `json:"valueWoVersion,omitempty" tf:"value_wo_version,omitempty"`
}

type BcryptPasswordObservation struct {

	// apply the write-only value.
	// Version of value_wo. Bump to re-apply the write-only value.
	ValueWoVersion *float64 `json:"valueWoVersion,omitempty" tf:"value_wo_version,omitempty"`
}

type BcryptPasswordParameters struct {

	// 11.
	// Authentication value stored in state.11. Exactly one of value or value_wo.
	// +kubebuilder:validation:Optional
	ValueSecretRef *v2.SecretKeySelector `json:"valueSecretRef,omitempty" tf:"-"`

	// 11).
	// Bump value_wo_version to re-apply the value.
	// Write-only authentication value, not stored in state.11.
	// +kubebuilder:validation:Optional
	ValueWoSecretRef *v2.SecretKeySelector `json:"valueWoSecretRef,omitempty" tf:"-"`

	// apply the write-only value.
	// Version of value_wo. Bump to re-apply the write-only value.
	// +kubebuilder:validation:Optional
	ValueWoVersion *float64 `json:"valueWoVersion,omitempty" tf:"value_wo_version,omitempty"`
}

type DoubleSha1HashInitParameters struct {

	// 11.
	// Authentication value stored in state.11. Exactly one of value or value_wo.
	ValueSecretRef *v2.SecretKeySelector `json:"valueSecretRef,omitempty" tf:"-"`

	// 11).
	// Bump value_wo_version to re-apply the value.
	// Write-only authentication value, not stored in state.11.
	ValueWoSecretRef *v2.SecretKeySelector `json:"valueWoSecretRef,omitempty" tf:"-"`

	// apply the write-only value.
	// Version of value_wo. Bump to re-apply the write-only value.
	ValueWoVersion *float64 `json:"valueWoVersion,omitempty" tf:"value_wo_version,omitempty"`
}

type DoubleSha1HashObservation struct {

	// apply the write-only value.
	// Version of value_wo. Bump to re-apply the write-only value.
	ValueWoVersion *float64 `json:"valueWoVersion,omitempty" tf:"value_wo_version,omitempty"`
}

type DoubleSha1HashParameters struct {

	// 11.
	// Authentication value stored in state.11. Exactly one of value or value_wo.
	// +kubebuilder:validation:Optional
	ValueSecretRef *v2.SecretKeySelector `json:"valueSecretRef,omitempty" tf:"-"`

	// 11).
	// Bump value_wo_version to re-apply the value.
	// Write-only authentication value, not stored in state.11.
	// +kubebuilder:validation:Optional
	ValueWoSecretRef *v2.SecretKeySelector `json:"valueWoSecretRef,omitempty" tf:"-"`

	// apply the write-only value.
	// Version of value_wo. Bump to re-apply the write-only value.
	// +kubebuilder:validation:Optional
	ValueWoVersion *float64 `json:"valueWoVersion,omitempty" tf:"value_wo_version,omitempty"`
}

type DoubleSha1PasswordInitParameters struct {

	// 11.
	// Authentication value stored in state.11. Exactly one of value or value_wo.
	ValueSecretRef *v2.SecretKeySelector `json:"valueSecretRef,omitempty" tf:"-"`

	// 11).
	// Bump value_wo_version to re-apply the value.
	// Write-only authentication value, not stored in state.11.
	ValueWoSecretRef *v2.SecretKeySelector `json:"valueWoSecretRef,omitempty" tf:"-"`

	// apply the write-only value.
	// Version of value_wo. Bump to re-apply the write-only value.
	ValueWoVersion *float64 `json:"valueWoVersion,omitempty" tf:"value_wo_version,omitempty"`
}

type DoubleSha1PasswordObservation struct {

	// apply the write-only value.
	// Version of value_wo. Bump to re-apply the write-only value.
	ValueWoVersion *float64 `json:"valueWoVersion,omitempty" tf:"value_wo_version,omitempty"`
}

type DoubleSha1PasswordParameters struct {

	// 11.
	// Authentication value stored in state.11. Exactly one of value or value_wo.
	// +kubebuilder:validation:Optional
	ValueSecretRef *v2.SecretKeySelector `json:"valueSecretRef,omitempty" tf:"-"`

	// 11).
	// Bump value_wo_version to re-apply the value.
	// Write-only authentication value, not stored in state.11.
	// +kubebuilder:validation:Optional
	ValueWoSecretRef *v2.SecretKeySelector `json:"valueWoSecretRef,omitempty" tf:"-"`

	// apply the write-only value.
	// Version of value_wo. Bump to re-apply the write-only value.
	// +kubebuilder:validation:Optional
	ValueWoVersion *float64 `json:"valueWoVersion,omitempty" tf:"value_wo_version,omitempty"`
}

type HTTPInitParameters struct {

	// (String) HTTP authentication scheme (e.g. Basic).
	// HTTP authentication scheme (e.g. Basic).
	Scheme *string `json:"scheme,omitempty" tf:"scheme,omitempty"`

	// (String) HTTP authentication server name.
	// HTTP authentication server name.
	Server *string `json:"server,omitempty" tf:"server,omitempty"`
}

type HTTPObservation struct {

	// (String) HTTP authentication scheme (e.g. Basic).
	// HTTP authentication scheme (e.g. Basic).
	Scheme *string `json:"scheme,omitempty" tf:"scheme,omitempty"`

	// (String) HTTP authentication server name.
	// HTTP authentication server name.
	Server *string `json:"server,omitempty" tf:"server,omitempty"`
}

type HTTPParameters struct {

	// (String) HTTP authentication scheme (e.g. Basic).
	// HTTP authentication scheme (e.g. Basic).
	// +kubebuilder:validation:Optional
	Scheme *string `json:"scheme,omitempty" tf:"scheme,omitempty"`

	// (String) HTTP authentication server name.
	// HTTP authentication server name.
	// +kubebuilder:validation:Optional
	Server *string `json:"server,omitempty" tf:"server,omitempty"`
}

type KerberosInitParameters struct {

	// (String) Optional Kerberos realm to restrict authentication to.
	// Optional Kerberos realm to restrict authentication to.
	Realm *string `json:"realm,omitempty" tf:"realm,omitempty"`
}

type KerberosObservation struct {

	// (String) Optional Kerberos realm to restrict authentication to.
	// Optional Kerberos realm to restrict authentication to.
	Realm *string `json:"realm,omitempty" tf:"realm,omitempty"`
}

type KerberosParameters struct {

	// (String) Optional Kerberos realm to restrict authentication to.
	// Optional Kerberos realm to restrict authentication to.
	// +kubebuilder:validation:Optional
	Realm *string `json:"realm,omitempty" tf:"realm,omitempty"`
}

type LdapInitParameters struct {

	// (String) HTTP authentication server name.
	// LDAP server name (as defined in ClickHouse config).
	Server *string `json:"server,omitempty" tf:"server,omitempty"`
}

type LdapObservation struct {

	// (String) HTTP authentication server name.
	// LDAP server name (as defined in ClickHouse config).
	Server *string `json:"server,omitempty" tf:"server,omitempty"`
}

type LdapParameters struct {

	// (String) HTTP authentication server name.
	// LDAP server name (as defined in ClickHouse config).
	// +kubebuilder:validation:Optional
	Server *string `json:"server" tf:"server,omitempty"`
}

type NoPasswordInitParameters struct {
}

type NoPasswordObservation struct {
}

type NoPasswordParameters struct {
}

type PlaintextPasswordInitParameters struct {

	// 11.
	// Authentication value stored in state.11. Exactly one of value or value_wo.
	ValueSecretRef *v2.SecretKeySelector `json:"valueSecretRef,omitempty" tf:"-"`

	// 11).
	// Bump value_wo_version to re-apply the value.
	// Write-only authentication value, not stored in state.11.
	ValueWoSecretRef *v2.SecretKeySelector `json:"valueWoSecretRef,omitempty" tf:"-"`

	// apply the write-only value.
	// Version of value_wo. Bump to re-apply the write-only value.
	ValueWoVersion *float64 `json:"valueWoVersion,omitempty" tf:"value_wo_version,omitempty"`
}

type PlaintextPasswordObservation struct {

	// apply the write-only value.
	// Version of value_wo. Bump to re-apply the write-only value.
	ValueWoVersion *float64 `json:"valueWoVersion,omitempty" tf:"value_wo_version,omitempty"`
}

type PlaintextPasswordParameters struct {

	// 11.
	// Authentication value stored in state.11. Exactly one of value or value_wo.
	// +kubebuilder:validation:Optional
	ValueSecretRef *v2.SecretKeySelector `json:"valueSecretRef,omitempty" tf:"-"`

	// 11).
	// Bump value_wo_version to re-apply the value.
	// Write-only authentication value, not stored in state.11.
	// +kubebuilder:validation:Optional
	ValueWoSecretRef *v2.SecretKeySelector `json:"valueWoSecretRef,omitempty" tf:"-"`

	// apply the write-only value.
	// Version of value_wo. Bump to re-apply the write-only value.
	// +kubebuilder:validation:Optional
	ValueWoVersion *float64 `json:"valueWoVersion,omitempty" tf:"value_wo_version,omitempty"`
}

type SSHKeyInitParameters struct {

	// (String) SSH public key.
	// SSH public key.
	PublicKey *string `json:"publicKey,omitempty" tf:"public_key,omitempty"`

	// rsa, ssh-ed25519).
	// SSH key type (e.g. ssh-rsa, ssh-ed25519).
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type SSHKeyObservation struct {

	// (String) SSH public key.
	// SSH public key.
	PublicKey *string `json:"publicKey,omitempty" tf:"public_key,omitempty"`

	// rsa, ssh-ed25519).
	// SSH key type (e.g. ssh-rsa, ssh-ed25519).
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type SSHKeyParameters struct {

	// (String) SSH public key.
	// SSH public key.
	// +kubebuilder:validation:Optional
	PublicKey *string `json:"publicKey" tf:"public_key,omitempty"`

	// rsa, ssh-ed25519).
	// SSH key type (e.g. ssh-rsa, ssh-ed25519).
	// +kubebuilder:validation:Optional
	Type *string `json:"type" tf:"type,omitempty"`
}

type SSLCertificateInitParameters struct {

	// (String) Certificate Common Name (CN).
	// Certificate Common Name (CN).
	CommonName *string `json:"commonName,omitempty" tf:"common_name,omitempty"`

	// (String) Certificate Subject Alternative Name (SAN).
	// Certificate Subject Alternative Name (SAN).
	SubjectAltName *string `json:"subjectAltName,omitempty" tf:"subject_alt_name,omitempty"`
}

type SSLCertificateObservation struct {

	// (String) Certificate Common Name (CN).
	// Certificate Common Name (CN).
	CommonName *string `json:"commonName,omitempty" tf:"common_name,omitempty"`

	// (String) Certificate Subject Alternative Name (SAN).
	// Certificate Subject Alternative Name (SAN).
	SubjectAltName *string `json:"subjectAltName,omitempty" tf:"subject_alt_name,omitempty"`
}

type SSLCertificateParameters struct {

	// (String) Certificate Common Name (CN).
	// Certificate Common Name (CN).
	// +kubebuilder:validation:Optional
	CommonName *string `json:"commonName,omitempty" tf:"common_name,omitempty"`

	// (String) Certificate Subject Alternative Name (SAN).
	// Certificate Subject Alternative Name (SAN).
	// +kubebuilder:validation:Optional
	SubjectAltName *string `json:"subjectAltName,omitempty" tf:"subject_alt_name,omitempty"`
}

type Sha256HashInitParameters struct {

	// (String) Optional salt used with the sha256 hash.
	// Optional salt used with the sha256 hash.
	Salt *string `json:"salt,omitempty" tf:"salt,omitempty"`

	// 11.
	// Authentication value stored in state.11. Exactly one of value or value_wo.
	ValueSecretRef *v2.SecretKeySelector `json:"valueSecretRef,omitempty" tf:"-"`

	// 11).
	// Bump value_wo_version to re-apply the value.
	// Write-only authentication value, not stored in state.11.
	ValueWoSecretRef *v2.SecretKeySelector `json:"valueWoSecretRef,omitempty" tf:"-"`

	// apply the write-only value.
	// Version of value_wo. Bump to re-apply the write-only value.
	ValueWoVersion *float64 `json:"valueWoVersion,omitempty" tf:"value_wo_version,omitempty"`
}

type Sha256HashObservation struct {

	// (String) Optional salt used with the sha256 hash.
	// Optional salt used with the sha256 hash.
	Salt *string `json:"salt,omitempty" tf:"salt,omitempty"`

	// apply the write-only value.
	// Version of value_wo. Bump to re-apply the write-only value.
	ValueWoVersion *float64 `json:"valueWoVersion,omitempty" tf:"value_wo_version,omitempty"`
}

type Sha256HashParameters struct {

	// (String) Optional salt used with the sha256 hash.
	// Optional salt used with the sha256 hash.
	// +kubebuilder:validation:Optional
	Salt *string `json:"salt,omitempty" tf:"salt,omitempty"`

	// 11.
	// Authentication value stored in state.11. Exactly one of value or value_wo.
	// +kubebuilder:validation:Optional
	ValueSecretRef *v2.SecretKeySelector `json:"valueSecretRef,omitempty" tf:"-"`

	// 11).
	// Bump value_wo_version to re-apply the value.
	// Write-only authentication value, not stored in state.11.
	// +kubebuilder:validation:Optional
	ValueWoSecretRef *v2.SecretKeySelector `json:"valueWoSecretRef,omitempty" tf:"-"`

	// apply the write-only value.
	// Version of value_wo. Bump to re-apply the write-only value.
	// +kubebuilder:validation:Optional
	ValueWoVersion *float64 `json:"valueWoVersion,omitempty" tf:"value_wo_version,omitempty"`
}

type Sha256PasswordInitParameters struct {

	// 11.
	// Authentication value stored in state.11. Exactly one of value or value_wo.
	ValueSecretRef *v2.SecretKeySelector `json:"valueSecretRef,omitempty" tf:"-"`

	// 11).
	// Bump value_wo_version to re-apply the value.
	// Write-only authentication value, not stored in state.11.
	ValueWoSecretRef *v2.SecretKeySelector `json:"valueWoSecretRef,omitempty" tf:"-"`

	// apply the write-only value.
	// Version of value_wo. Bump to re-apply the write-only value.
	ValueWoVersion *float64 `json:"valueWoVersion,omitempty" tf:"value_wo_version,omitempty"`
}

type Sha256PasswordObservation struct {

	// apply the write-only value.
	// Version of value_wo. Bump to re-apply the write-only value.
	ValueWoVersion *float64 `json:"valueWoVersion,omitempty" tf:"value_wo_version,omitempty"`
}

type Sha256PasswordParameters struct {

	// 11.
	// Authentication value stored in state.11. Exactly one of value or value_wo.
	// +kubebuilder:validation:Optional
	ValueSecretRef *v2.SecretKeySelector `json:"valueSecretRef,omitempty" tf:"-"`

	// 11).
	// Bump value_wo_version to re-apply the value.
	// Write-only authentication value, not stored in state.11.
	// +kubebuilder:validation:Optional
	ValueWoSecretRef *v2.SecretKeySelector `json:"valueWoSecretRef,omitempty" tf:"-"`

	// apply the write-only value.
	// Version of value_wo. Bump to re-apply the write-only value.
	// +kubebuilder:validation:Optional
	ValueWoVersion *float64 `json:"valueWoVersion,omitempty" tf:"value_wo_version,omitempty"`
}

type UserInitParameters struct {

	// (String) Name of the cluster to create the resource into. If omitted, resource will be created on the replica hit by the query.
	// This field must be left null when using a ClickHouse Cloud cluster.
	// When using a self hosted ClickHouse instance, this field should only be set when there is more than one replica and you are not using 'replicated' storage for user_directory.
	// Name of the cluster to create the resource into. If omitted, resource will be created on the replica hit by the query.
	// This field must be left null when using a ClickHouse Cloud cluster.
	// When using a self hosted ClickHouse instance, this field should only be set when there is more than one replica and you are not using 'replicated' storage for user_directory.
	ClusterName *string `json:"clusterName,omitempty" tf:"cluster_name,omitempty"`

	// (Set of String) IP addresses from which the user is allowed to connect. If not specified, user can connect from any host.
	// IP addresses from which the user is allowed to connect. If not specified, user can connect from any host.
	// +listType=set
	HostIps []*string `json:"hostIps,omitempty" tf:"host_ips,omitempty"`

	// (String) Name of the user
	// Name of the user
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String, Sensitive, Deprecated) SHA256 hash of the password to be set for the user.11. Conflicts with password_sha256_hash_wo. Changes to this field will replace the user.
	// Reference to a secret containing the SHA256 hash of the password. This field is automatically set.
	PasswordSha256HashSecretRef *v2.SecretKeySelector `json:"passwordSha256HashSecretRef,omitempty" tf:"-"`
}

type UserObservation struct {

	// (Block, Optional) Authentication methods for the user. Methods may be combined and each block (except no_password) may be repeated. (see below for nested schema)
	// Authentication methods for the user. Methods may be combined and each block (except no_password) may be repeated.
	Auth []AuthObservation `json:"auth,omitempty" tf:"auth,omitempty"`

	// (String) Name of the cluster to create the resource into. If omitted, resource will be created on the replica hit by the query.
	// This field must be left null when using a ClickHouse Cloud cluster.
	// When using a self hosted ClickHouse instance, this field should only be set when there is more than one replica and you are not using 'replicated' storage for user_directory.
	// Name of the cluster to create the resource into. If omitted, resource will be created on the replica hit by the query.
	// This field must be left null when using a ClickHouse Cloud cluster.
	// When using a self hosted ClickHouse instance, this field should only be set when there is more than one replica and you are not using 'replicated' storage for user_directory.
	ClusterName *string `json:"clusterName,omitempty" tf:"cluster_name,omitempty"`

	// (Set of String) IP addresses from which the user is allowed to connect. If not specified, user can connect from any host.
	// IP addresses from which the user is allowed to connect. If not specified, user can connect from any host.
	// +listType=set
	HostIps []*string `json:"hostIps,omitempty" tf:"host_ips,omitempty"`

	// assigned ID for the user
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Name of the user
	// Name of the user
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type UserParameters struct {

	// If true, a password is auto-generated and stored in the secret referenced by writeConnectionSecretToRef under keys 'password' (plaintext) and 'hash' (SHA256). The passwordSha256HashSecretRef field is set automatically - no other password fields need to be configured.
	// +upjet:crd:field:TFTag=-
	// +kubebuilder:validation:Optional
	AutoGeneratePassword *bool `json:"autoGeneratePassword,omitempty" tf:"-"`

	// (String) Name of the cluster to create the resource into. If omitted, resource will be created on the replica hit by the query.
	// This field must be left null when using a ClickHouse Cloud cluster.
	// When using a self hosted ClickHouse instance, this field should only be set when there is more than one replica and you are not using 'replicated' storage for user_directory.
	// Name of the cluster to create the resource into. If omitted, resource will be created on the replica hit by the query.
	// This field must be left null when using a ClickHouse Cloud cluster.
	// When using a self hosted ClickHouse instance, this field should only be set when there is more than one replica and you are not using 'replicated' storage for user_directory.
	// +kubebuilder:validation:Optional
	ClusterName *string `json:"clusterName,omitempty" tf:"cluster_name,omitempty"`

	// (Set of String) IP addresses from which the user is allowed to connect. If not specified, user can connect from any host.
	// IP addresses from which the user is allowed to connect. If not specified, user can connect from any host.
	// +kubebuilder:validation:Optional
	// +listType=set
	HostIps []*string `json:"hostIps,omitempty" tf:"host_ips,omitempty"`

	// (String) Name of the user
	// Name of the user
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Reference to a user-owned secret containing the plaintext password. The controller reads the plaintext, computes its SHA256 hash, and writes the hash back to the same secret under key 'hash'. This field is mutually exclusive with autoGeneratePassword.
	// +upjet:crd:field:TFTag=-
	// +kubebuilder:validation:Optional
	// +mapType=granular
	PasswordSecretRef map[string]*string `json:"passwordSecretRef,omitempty" tf:"-"`

	// (String, Sensitive, Deprecated) SHA256 hash of the password to be set for the user.11. Conflicts with password_sha256_hash_wo. Changes to this field will replace the user.
	// Reference to a secret containing the SHA256 hash of the password. This field is automatically set.
	// +kubebuilder:validation:Optional
	PasswordSha256HashSecretRef *v2.SecretKeySelector `json:"passwordSha256HashSecretRef,omitempty" tf:"-"`
}

// UserSpec defines the desired state of User
type UserSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   UserParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider UserInitParameters `json:"initProvider,omitempty"`
}

// UserStatus defines the observed state of User.
type UserStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               UserObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// User is the Schema for the Users API. You can use the clickhousedbops_user resource to create a user in a ClickHouse instance. Password can be either autogenerated or referenced from an existing Kubernetes Secret. Changing the password will cause the database user to be deleted and recreated
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,clickhousedbops}
type User struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   UserSpec   `json:"spec"`
	Status UserStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// UserList contains a list of Users
type UserList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []User `json:"items"`
}

// Repository type metadata.
var (
	User_Kind             = "User"
	User_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: User_Kind}.String()
	User_KindAPIVersion   = User_Kind + "." + CRDGroupVersion.String()
	User_GroupVersionKind = CRDGroupVersion.WithKind(User_Kind)
)

func init() {
	SchemeBuilder.Register(&User{}, &UserList{})
}
