package config

import (
	"github.com/crossplane/upjet/v2/pkg/config"
	"github.com/crossplane/upjet/v2/pkg/types/comments"
	tfschema "github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

// terraformedObservation is the subset of upjet's resource.Terraformed that we
// need to read and write the Terraform observation (status.atProvider).
type terraformedObservation interface {
	GetObservation() (map[string]any, error)
	SetObservation(map[string]any) error
}

var gkvOverrideMap = map[string]schema.GroupVersionKind{
	"clickhousedbops_grant_privilege": {
		Group: "",
		Kind:  "GrantPrivilege",
	},
	"clickhousedbops_grant_role": {
		Group: "",
		Kind:  "GrantRole",
	},
	"clickhousedbops_settings_profile": {
		Group: "",
		Kind:  "SettingProfile",
	},
	"clickhousedbops_settings_profile_association": {
		Group: "",
		Kind:  "SettingProfileAssociation",
	},
}

func gvkOverride() config.ResourceOption {
	return func(r *config.Resource) {
		if r.ShortGroup == resourcePrefix {
			r.ShortGroup = ""
		}
		if gvk, ok := gkvOverrideMap[r.Name]; ok {
			r.ShortGroup = gvk.Group
			r.Kind = gvk.Kind
			if gvk.Version != "" {
				r.Version = gvk.Version
			}
		}
	}
}

func Configure(p *config.Provider) {
	p.AddResourceConfigurator("clickhousedbops_database", func(r *config.Resource) {
		// When reconciling a clickhousedbops_database resource, the provider calls a Read operation
		// to check if the resource exists by looking up the database by uuid.
		// But it reads that uuid from the previous Terraform state, not from the resource name.
		// Before that, adoptByNameInitializer seeds status.atProvider.uuid: the real UUID when a
		// database of that name already exists (adopt/import), otherwise the sentinelUUID.
		// When upjet builds the Terraform state file from that observation, the provider now has a
		// valid UUID to send to ClickHouse. A real UUID imports the existing database; the sentinel
		// matches no row, which the provider maps to "not found", triggering resource creation.
		r.InitializerFns = append(r.InitializerFns, adoptByNameInitializer("clickhousedbops_database", "uuid"))
		r.UseAsync = true
	})
	p.AddResourceConfigurator("clickhousedbops_user", func(r *config.Resource) {
		// Removing "id" from the schema keeps hasTFID=false, so EnsureTFState falls
		// back to status.atProvider.id (seeded by adoptByNameInitializer). ClickHouse
		// finds no rows for the sentinel UUID and returns zero rows, which the provider
		// maps to "not found", triggering creation; a resolved real UUID imports the
		// existing user instead. After creation, atProvider holds the real UUID and the
		// initializer leaves it untouched on subsequent reconciles.
		// The "id" field still appears in status.atProvider because the provider
		// populates it from its own TF state output after a successful read.
		delete(r.TerraformResource.Schema, "id")
		r.MetaResource.Description = ("You can use the clickhousedbops_user resource to create a user in a ClickHouse instance. " +
			"Password can be either autogenerated or referenced from an existing Kubernetes Secret. " +
			"Changing the password will cause the database user to be deleted and recreated")

		desc, _ := comments.New("If true, a password is auto-generated and stored in"+
			" the secret referenced by writeConnectionSecretToRef under keys"+
			" 'password' (plaintext) and 'hash' (SHA256). The passwordSha256HashSecretRef"+
			" field is set automatically - no other password fields need to be configured.",
			comments.WithTFTag("-"))
		r.TerraformResource.Schema["auto_generate_password"] = &tfschema.Schema{
			Type:        tfschema.TypeBool,
			Optional:    true,
			Description: desc.String(),
		}

		descSecretRef, _ := comments.New("Reference to a user-owned secret containing the plaintext password."+
			" The controller reads the plaintext, computes its SHA256 hash, and writes the hash back"+
			" to the same secret under key 'hash'. Supports password rotation: updating the plaintext"+
			" triggers a hash update on the next reconcile, which causes the Terraform provider to update ClickHouse."+
			" This field is mutually exclusive with autoGeneratePassword.",
			comments.WithTFTag("-"))
		r.TerraformResource.Schema["password_secret_ref"] = &tfschema.Schema{
			Type:        tfschema.TypeMap,
			Optional:    true,
			Description: descSecretRef.String(),
			Elem: &tfschema.Schema{
				Type: tfschema.TypeString,
			},
		}

		r.InitializerFns = append(r.InitializerFns,
			PasswordValidator(),
			PasswordRefProcessor(),
			adoptByNameInitializer("clickhousedbops_user", "id"),
			PasswordGenerator("spec.forProvider.autoGeneratePassword"),
		)

		s, ok := r.TerraformResource.Schema["password_sha256_hash"]
		if ok {
			s.Description = "Reference to a secret containing the SHA256 hash of the password. " +
				"This field is automatically set."
		}

		// Remove write-only fields that require Terraform >=1.11.
		// This provider targets Terraform <=1.5; users must use
		// passwordSha256HashSecretRef (or autoGeneratePassword) instead.
		r.ExternalName.OmittedFields = []string{
			"password_sha256_hash_wo",
			"password_sha256_hash_wo_version",
		}
	})
	p.AddResourceConfigurator("clickhousedbops_settings_profile", func(r *config.Resource) {
		// Same hasTFID=false trick as for clickhousedbops_user, prevents name-based
		// id from being written to TF state on first reconcile, avoiding UUID parse errors.
		delete(r.TerraformResource.Schema, "id")
		r.InitializerFns = append(r.InitializerFns, adoptByNameInitializer("clickhousedbops_settings_profile", "id"))
	})
	p.AddResourceConfigurator("clickhousedbops_role", func(r *config.Resource) {
		// Same hasTFID=false trick, role lookup also uses UUID-based WHERE id=UUID(...).
		delete(r.TerraformResource.Schema, "id")
		// Roles must be adoptable: after a backup restore the role already exists in
		// ClickHouse and CREATE ROLE (which is not idempotent) fails with
		// "already exists in `replicated`". adoptByNameInitializer looks the role up
		// by name and seeds its real UUID when found, so upjet imports instead of
		// re-creating; it falls back to the sentinel (force-create) when absent.
		r.InitializerFns = append(r.InitializerFns, adoptByNameInitializer("clickhousedbops_role", "id"))
	})
	p.AddResourceConfigurator("clickhousedbops_grant_privilege", func(r *config.Resource) {
		r.InitializerFns = append(r.InitializerFns, backfillGrantPrivilegeDefaults())
		r.References["grantee_role_name"] = config.Reference{
			TerraformName: "clickhousedbops_role",
		}
		r.References["grantee_user_name"] = config.Reference{
			TerraformName: "clickhousedbops_user",
		}
		r.References["database_name"] = config.Reference{
			TerraformName: "clickhousedbops_database",
		}
	})
	p.AddResourceConfigurator("clickhousedbops_grant_role", func(r *config.Resource) {
		r.References["role_name"] = config.Reference{
			TerraformName: "clickhousedbops_role",
		}
		r.References["grantee_role_name"] = config.Reference{
			TerraformName: "clickhousedbops_role",
		}
		r.References["grantee_user_name"] = config.Reference{
			TerraformName: "clickhousedbops_user",
		}
	})
	p.AddResourceConfigurator("clickhousedbops_masking_policy", func(r *config.Resource) {
		r.ExternalName = config.TemplatedStringAsIdentifier("name", "{{ .parameters.database_name }}:{{ .parameters.table_name }}:{{ .externalName }}")
		r.References["database_name"] = config.Reference{
			TerraformName: "clickhousedbops_database",
		}
	})
	p.AddResourceConfigurator("clickhousedbops_row_policy", func(r *config.Resource) {
		r.ExternalName = config.TemplatedStringAsIdentifier("name", "{{ .parameters.database_name }}:{{ .parameters.table_name }}:{{ .externalName }}")
		r.References["database_name"] = config.Reference{
			TerraformName: "clickhousedbops_database",
		}
	})
}
