apiVersion: clickhousedbops.crossplane.io/v1alpha1
kind: GrantPrivilege
metadata:
  annotations:
    meta.upbound.io/example-id: clickhousedbops/v1alpha1/grantprivilege
    # ClickHouse does not support importing grants; skip the import phase.
    uptest.upbound.io/skip-import: "true"
    uptest.upbound.io/dependencies: testuser,testdb
  labels:
    testing.upbound.io/example-name: testgrantprivilege
  name: testgrantprivilege
spec:
  forProvider:
    databaseName: testdb
    granteeUserName: testuser
    privilegeName: SELECT
