// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type PolicyInitParameters struct {

	// (String) Name of the cluster to create the resource into. If omitted, resource will be created on the replica hit by the query.
	// This field must be left null when using a ClickHouse Cloud cluster.
	// Name of the cluster to create the resource into. If omitted, resource will be created on the replica hit by the query.
	// This field must be left null when using a ClickHouse Cloud cluster.
	ClusterName *string `json:"clusterName,omitempty" tf:"cluster_name,omitempty"`

	// : apply to all users and roles, excluding the ones listed. An empty set ([]) applies to everyone with no exclusions.
	// Apply the row policy to all users and roles, excluding those listed. An empty set applies to everyone with no exclusions.
	// +listType=set
	GranteeAllExcept []*string `json:"granteeAllExcept,omitempty" tf:"grantee_all_except,omitempty"`

	// : a list of user and role names. ClickHouse stores these as one untyped list and resolves each name to a user before a role, so users and roles are not distinguished here.
	// Set of user or role names the row policy applies to. ClickHouse stores these as one untyped grantee list and resolves each name to a user before a role, so users and roles are not distinguished here.
	// +listType=set
	GranteeNames []*string `json:"granteeNames,omitempty" tf:"grantee_names,omitempty"`

	// (Boolean) If true, the policy is restrictive (AND logic). If false (default), the policy is permissive (OR logic).
	// If true, the policy is restrictive (AND logic). If false (default), the policy is permissive (OR logic).
	IsRestrictive *bool `json:"isRestrictive,omitempty" tf:"is_restrictive,omitempty"`

	// (String) The filter expression used in the USING clause. For example: tenant_id = 'abc'.
	// The filter expression used in the USING clause. For example: `tenant_id = 'abc'`.
	SelectFilter *string `json:"selectFilter,omitempty" tf:"select_filter,omitempty"`
}

type PolicyObservation struct {

	// (String) Name of the cluster to create the resource into. If omitted, resource will be created on the replica hit by the query.
	// This field must be left null when using a ClickHouse Cloud cluster.
	// Name of the cluster to create the resource into. If omitted, resource will be created on the replica hit by the query.
	// This field must be left null when using a ClickHouse Cloud cluster.
	ClusterName *string `json:"clusterName,omitempty" tf:"cluster_name,omitempty"`

	// (String) The database of the table to apply the row policy to. Must be a concrete name; wildcards (*) are not supported.
	// The database of the table to apply the row policy to. Must be a concrete name; wildcards (`*`) are not supported.
	DatabaseName *string `json:"databaseName,omitempty" tf:"database_name,omitempty"`

	// : apply to all users and roles, excluding the ones listed. An empty set ([]) applies to everyone with no exclusions.
	// Apply the row policy to all users and roles, excluding those listed. An empty set applies to everyone with no exclusions.
	// +listType=set
	GranteeAllExcept []*string `json:"granteeAllExcept,omitempty" tf:"grantee_all_except,omitempty"`

	// : a list of user and role names. ClickHouse stores these as one untyped list and resolves each name to a user before a role, so users and roles are not distinguished here.
	// Set of user or role names the row policy applies to. ClickHouse stores these as one untyped grantee list and resolves each name to a user before a role, so users and roles are not distinguished here.
	// +listType=set
	GranteeNames []*string `json:"granteeNames,omitempty" tf:"grantee_names,omitempty"`

	// assigned ID for the row policy.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Boolean) If true, the policy is restrictive (AND logic). If false (default), the policy is permissive (OR logic).
	// If true, the policy is restrictive (AND logic). If false (default), the policy is permissive (OR logic).
	IsRestrictive *bool `json:"isRestrictive,omitempty" tf:"is_restrictive,omitempty"`

	// (String) The filter expression used in the USING clause. For example: tenant_id = 'abc'.
	// The filter expression used in the USING clause. For example: `tenant_id = 'abc'`.
	SelectFilter *string `json:"selectFilter,omitempty" tf:"select_filter,omitempty"`

	// (String) The table to apply the row policy to. Must be a concrete name; wildcards (*) are not supported.
	// The table to apply the row policy to. Must be a concrete name; wildcards (`*`) are not supported.
	TableName *string `json:"tableName,omitempty" tf:"table_name,omitempty"`
}

type PolicyParameters struct {

	// (String) Name of the cluster to create the resource into. If omitted, resource will be created on the replica hit by the query.
	// This field must be left null when using a ClickHouse Cloud cluster.
	// Name of the cluster to create the resource into. If omitted, resource will be created on the replica hit by the query.
	// This field must be left null when using a ClickHouse Cloud cluster.
	// +kubebuilder:validation:Optional
	ClusterName *string `json:"clusterName,omitempty" tf:"cluster_name,omitempty"`

	// (String) The database of the table to apply the row policy to. Must be a concrete name; wildcards (*) are not supported.
	// The database of the table to apply the row policy to. Must be a concrete name; wildcards (`*`) are not supported.
	// +crossplane:generate:reference:type=Database
	// +kubebuilder:validation:Optional
	DatabaseName *string `json:"databaseName,omitempty" tf:"database_name,omitempty"`

	// Reference to a Database to populate databaseName.
	// +kubebuilder:validation:Optional
	DatabaseNameRef *v2.Reference `json:"databaseNameRef,omitempty" tf:"-"`

	// Selector for a Database to populate databaseName.
	// +kubebuilder:validation:Optional
	DatabaseNameSelector *v2.Selector `json:"databaseNameSelector,omitempty" tf:"-"`

	// : apply to all users and roles, excluding the ones listed. An empty set ([]) applies to everyone with no exclusions.
	// Apply the row policy to all users and roles, excluding those listed. An empty set applies to everyone with no exclusions.
	// +kubebuilder:validation:Optional
	// +listType=set
	GranteeAllExcept []*string `json:"granteeAllExcept,omitempty" tf:"grantee_all_except,omitempty"`

	// : a list of user and role names. ClickHouse stores these as one untyped list and resolves each name to a user before a role, so users and roles are not distinguished here.
	// Set of user or role names the row policy applies to. ClickHouse stores these as one untyped grantee list and resolves each name to a user before a role, so users and roles are not distinguished here.
	// +kubebuilder:validation:Optional
	// +listType=set
	GranteeNames []*string `json:"granteeNames,omitempty" tf:"grantee_names,omitempty"`

	// (Boolean) If true, the policy is restrictive (AND logic). If false (default), the policy is permissive (OR logic).
	// If true, the policy is restrictive (AND logic). If false (default), the policy is permissive (OR logic).
	// +kubebuilder:validation:Optional
	IsRestrictive *bool `json:"isRestrictive,omitempty" tf:"is_restrictive,omitempty"`

	// (String) The filter expression used in the USING clause. For example: tenant_id = 'abc'.
	// The filter expression used in the USING clause. For example: `tenant_id = 'abc'`.
	// +kubebuilder:validation:Optional
	SelectFilter *string `json:"selectFilter,omitempty" tf:"select_filter,omitempty"`

	// (String) The table to apply the row policy to. Must be a concrete name; wildcards (*) are not supported.
	// The table to apply the row policy to. Must be a concrete name; wildcards (`*`) are not supported.
	// +kubebuilder:validation:Required
	TableName *string `json:"tableName" tf:"table_name,omitempty"`
}

// PolicySpec defines the desired state of Policy
type PolicySpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   PolicyParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider PolicyInitParameters `json:"initProvider,omitempty"`
}

// PolicyStatus defines the observed state of Policy.
type PolicyStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               PolicyObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Policy is the Schema for the Policys API. Manages a ClickHouse row policy, which restricts the rows a user or role can access when querying a table. ~> Important: When a row policy is created on a table, all users and roles without a matching policy will see zero rows from that table. You must create an additional permissive policy (e.g. USING 1 to ALL EXCEPT ...) for any users or roles that should retain full access. Resource can be imported by id or
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,clickhousedbops}
type Policy struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.selectFilter) || (has(self.initProvider) && has(self.initProvider.selectFilter))",message="spec.forProvider.selectFilter is a required parameter"
	Spec   PolicySpec   `json:"spec"`
	Status PolicyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PolicyList contains a list of Policys
type PolicyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Policy `json:"items"`
}

// Repository type metadata.
var (
	Policy_Kind             = "Policy"
	Policy_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Policy_Kind}.String()
	Policy_KindAPIVersion   = Policy_Kind + "." + CRDGroupVersion.String()
	Policy_GroupVersionKind = CRDGroupVersion.WithKind(Policy_Kind)
)

func init() {
	SchemeBuilder.Register(&Policy{}, &PolicyList{})
}
