name: Publish Provider Package

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version string to use while publishing the package (e.g. v1.0.0-alpha.1)
        default: ''
        required: false
      go-version:
        description: Go version to use if building needs to be done
        default: '1.26'
        required: false

jobs:
  publish-provider-package:
    uses: crossplane-contrib/provider-workflows/.github/workflows/publish-provider.yml@main
    with:
      cleanup-disk: true
      go-version: ${{ github.event.inputs.go-version }}
      mirror: false
      registry_org: lansweeper-oss
      repository: provider-clickhousedbops
      version: ${{ github.event.inputs.version }}
    secrets:
      GHCR_PAT: ${{ secrets.GITHUB_TOKEN }}

  mirror-to-upbound:
    needs: publish-provider-package
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.version != '' }}
    steps:
      - name: Setup crane
        uses: imjasonh/setup-crane@6da1ae018866400525525ce74ff892880c099987 # v0.5

      - name: Login to Upbound
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4
        with:
          registry: xpkg.upbound.io
          username: ${{ secrets.XPKG_MIRROR_ACCESS_ID }}
          password: ${{ secrets.XPKG_MIRROR_TOKEN }}

      - name: Mirror to Upbound
        run: |
          crane copy ghcr.io/lansweeper-oss/provider-clickhousedbops:${{ github.event.inputs.version }} xpkg.upbound.io/lansweeper/provider-clickhousedbops:${{ github.event.inputs.version }} --allow-nondistributable-artifacts
